server:
  port: 7001



eureka:
  instance:
    # eureka 服务端的实例名称
    hostname: localhost7001 # eureka 服务端的实例名称
    ip-address: 192.168.1.66,192.168.1.77
  client:
    # false 表示eureka不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，本服务端的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
##       设置与eureka server 交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/

