mysql.driver=com.mysql.jdbc.Driver  
mysql.url=jdbc:mysql://localhost:3306/test  
mysql.username=root
mysql.password=root

#//???????????????? 8 ???????????
#maxTotal=30
#//????????????????????5??????
#initialSize=5
#//???????
#maxActive=20
#//??????
#maxIdle=15
#//??????
#minIdle=1
#//????????
#maxWait=60000
